Apply LUA api providers before loading script.
makspll/bevy_mod_scripting pull request #98
Opened 2024-01-19 03:38 UTC by ConnorBP

Fixes issue where api is not available during script initialization. https://github.com/makspll/bevy_mod_scripting/issues/97

PR is not yet complete. There is still a `callback error` caused by: error converting Lua nil to userdata to investigate which happens when the api function is called.

2024-01-21 03:50 UTC, ConnorBP commented
Found what is causing the NIL error. It happened upon fetching the bevy "world" from globals. It is not set on script load execution, only after event execution is fired. This makes it so that any API function which accesses world state cannot be used during script load. To fix this requires a refactor involving changing the `script_add_synchronizer` into an `exclusive system` with a `SystemState`

2024-01-21 21:46 UTC, ConnorBP commented
Update: the other issues have their own concerns that should be in another PR. But the api registration issue is solved by this PR and should be considered Complete.

I will open a different PR for potential api refactoring for connecting callback functions with event signals.

2024-01-22 07:24 UTC, makspll requested changes
Looks good, just one small nit

2024-01-22 07:24 UTC, makspll commented on languages/bevy_mod_scripting_lua/src/lib.rs
> +        let mut lua = Mutex::new(lua);
Could we wrap in the mutex at the end instead?

2024-01-23 18:30 UTC, ConnorBP commented
> Looks good, just one small nit

`providers.attach_all()' requires a mutex as it's argument.

2024-01-24 12:05 UTC, makspll commented
Sounds good, let's just fix CI and happy to merge

2024-01-25 16:26 UTC, makspll approved these changes

2024-01-25 16:26 UTC, merged